# format: [time, velocity, angular vel]
turn_left: 
  - [0.9, 0.38, 0]
  - [1.2, 0.38, 2.2]
  - [0.2, 0.38, 0.0]
turn_right:
  - [0.3, 0.38, 0]
  - [1.1, 0.38,-2.9]
  - [0.2, 0.38, 0.0]
turn_forward:
  - [1.2, 0.38, -0.1]
