# format: [time, velocity, angular vel]
turn_left: 
  - [0.4, 0.38, 0]
  - [1.4, 0.38, 2.8]
  - [0.4, 0.38, 0.0]
turn_right:
  - [0.6, 0.38, 0]
  - [0.9, 0.30,-2.8]
  - [0.4, 0.38, 0.0]
turn_forward:
  - [0.4, 0.38, 0.0]
